spring:
  application:
    name: kafka
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: your_group_id
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.example.kafka.models.DTO" # Укажите пакет, где находится UserDto
        spring.json.value.default.type: "com.example.kafka.models.DTO.AbstractKafkaDTO" # Укажите пакет, где находится UserDto
        spring.json.fail-on-unknown-properties: false
    admin:
      auto-create: true

  datasource:
    url: jdbc:postgresql://localhost:5434/mydatabase
    username: myuser
    password: secret
    driver-class-name: org.postgresql.Driver

kafka-variable:
  topic-key: asdf
